/**
 * TypeScript type definitions for the LawAgent review API.
 *
 * These interfaces mirror the Pydantic response models exposed by the
 * FastAPI backend in `law_agent/review/api.py` and its dependencies
 * (`law_agent/review/schemas.py`, `law_agent/review/evalset/schemas.py`,
 * `law_agent/data/schemas.py`).
 *
 * Field names and JSON shapes are kept in sync with the backend so that
 * responses can be consumed directly without any client-side mapping.
 */

// ---------------------------------------------------------------------------
// Shared literal union types
// ---------------------------------------------------------------------------

/** Risk level reported by a review result. */
export type RiskLevel =
  | 'high'
  | 'medium'
  | 'low'
  | 'insufficient_evidence';

/** Usage category for a group of citations. */
export type CitationUsage =
  | 'legal_basis'
  | 'conditional_basis'
  | 'implementation_reference'
  | 'policy_explanation';

/** Role a clause citation plays in the legal argument. */
export type ClauseCitationRole =
  | 'primary_legal_basis'
  | 'conditional_local_basis'
  | 'conditional_industry_basis'
  | 'implementation_reference'
  | 'interpretation_auxiliary';

/** Status of the evidence sufficiency self-check. */
export type EvidenceStatus =
  | 'not_checked'
  | 'sufficient'
  | 'needs_second_retrieval'
  | 'insufficient';

/** Concrete issue types detected during the evidence self-check. */
export type EvidenceIssueType =
  | 'no_primary_legal_basis'
  | 'region_mismatch'
  | 'industry_mismatch'
  | 'only_auxiliary_evidence'
  | 'cross_border_mismatch'
  | 'critical_facts_missing';

/** Retrieval query type generated by the planner. */
export type RetrievalQueryType =
  | 'legal_issue'
  | 'material_fact'
  | 'region_condition'
  | 'industry_condition'
  | 'missing_information';

/** Retriever name used to produce a hit. */
export type RetrieverName =
  | 'keyword'
  | 'vector_mock'
  | 'hybrid'
  | 'elasticsearch'
  | 'pgvector';

/** Evaluation retrieval backend under test. */
export type EvalRetrievalMode = 'service' | 'local';

/** Evaluation review owner under test. */
export type EvalReviewMode = 'llm' | 'local' | 'multi_agent';

/** Optional post-fusion reranker arm for A/B evaluation. */
export type EvalRerankMode = 'off' | 'embedding';

/** Evaluation scenario subset. */
export type EvalSuite = 'quick' | 'base' | 'full';

// ---------------------------------------------------------------------------
// Review domain models
// ---------------------------------------------------------------------------

/**
 * Structured facts extracted from the user-supplied material.
 *
 * Matches `ReviewFacts` in `law_agent/review/schemas.py`. All optional
 * fields are `null` when the fact could not be inferred from the material.
 */
export interface ReviewFacts {
  /** High-level description of the business activity, if detected. */
  business_activity: string | null;
  /** Data categories referenced by the material (e.g. "personal_info"). */
  data_types: string[];
  /** Whether sensitive personal information is involved. */
  sensitive_personal_info: boolean | null;
  /** Whether cross-border data transfer is involved. */
  cross_border_transfer: boolean | null;
  /** The overseas recipient, if any. */
  overseas_recipient: string | null;
  /** Stated processing purpose. */
  processing_purpose: string | null;
  /** Legal basis or consent description claimed by the material. */
  legal_basis_or_consent: string | null;
  /** Industry context (e.g. "finance", "healthcare"). */
  industry: string | null;
  /** Geographic region context (e.g. "CN", "EU"). */
  region: string | null;
  /** Facts that could not be determined and should be requested from the user. */
  missing_information: string[];
}

/**
 * A governed citation selected for a review result.
 *
 * Matches `Citation` in `law_agent/review/schemas.py`.
 */
export interface Citation {
  source_id: string;
  chunk_id: string;
  title: string;
  source_url: string;
  citation_role: ClauseCitationRole;
  /** Whether this citation may be quoted as a formal clause. */
  can_cite_clause: boolean;
  usage: CitationUsage;
  /** Human-readable label for the citation (e.g. "《个人信息保护法》第38条"). */
  citation_label: string | null;
  /** Stable, case-local public reference (e.g. 法源-01). */
  citation_ref: string;
  article_no: string | null;
  full_article_text: string | null;
  doc_type: string;
  authority: string;
  law_status: string;
  publish_date: string | null;
  effective_date: string | null;
  issuing_body: string | null;
  heading_path: string[];
}

/**
 * A group of citations sharing the same usage category.
 *
 * Matches `CitationGroup` in `law_agent/review/schemas.py`.
 */
export interface CitationGroup {
  usage: CitationUsage;
  citations: Citation[];
  /** Optional note describing the scope of this group. */
  scope_note: string | null;
}

/** One conclusion claim and the evidence chunks that support it. */
export interface GroundedClaim {
  text: string;
  supporting_chunk_ids: string[];
  /** Server-resolved public refs; the UI must not infer these from position. */
  supporting_citation_refs: string[];
}

/**
 * A specific evidence sufficiency issue detected during self-check.
 *
 * Matches `EvidenceIssue` in `law_agent/review/schemas.py`.
 */
export interface EvidenceIssue {
  issue_type: EvidenceIssueType;
  description: string;
}

/**
 * A typed query generated for retrieval.
 *
 * Matches `RetrievalQuery` in `law_agent/review/schemas.py`. Referenced by
 * `SecondRetrievalPlan.expanded_queries`.
 */
export interface RetrievalQuery {
  query_id: string;
  query_type: RetrievalQueryType;
  text: string;
}

/**
 * A scored evidence hit returned by a retriever.
 *
 * Matches `RetrievalHit` in `law_agent/review/schemas.py`. Surfaced in the
 * review response as `evidence_chunks` so the frontend can expand a citation
 * to show the underlying clause text, source URL, and retrieval metadata.
 */
export interface RetrievalHit {
  chunk_id: string;
  doc_id: string;
  source_id: string;
  title: string;
  text: string;
  score: number;
  rank: number;
  retriever: RetrieverName;
  citation_role: ClauseCitationRole;
  can_cite_clause: boolean;
  source_url: string;
  matched_query_type: RetrievalQueryType | null;
  /** 条款编号（如 "第三十九条"），仅 can_cite_clause=true 的法条 chunk 有值。 */
  article_no: string | null;
  /** 引用标签（如 "《个人信息保护法》第三十九条"），用于引用卡片标题。 */
  citation_label: string | null;
  /** 标题路径（章节上下文），用于证据面板展示。 */
  heading_path: string[];
  doc_type: string;
  authority: string;
  law_status: string;
  publish_date: string | null;
  effective_date: string | null;
  issuing_body: string | null;
  full_article_text: string | null;
}

/**
 * Chunk-level evidence retained for one selected source.
 *
 * The backend uses source-aware fusion to pick diverse sources, then attaches
 * same-source supporting chunks and neighbor chunks so the report and UI keep
 * the precise passages behind each source.
 */
export interface SourceEvidencePacket {
  source_id: string;
  title: string;
  representative_chunk: RetrievalHit;
  supporting_chunks: RetrievalHit[];
  neighbor_chunks: RetrievalHit[];
}

/**
 * Plan for one controlled second retrieval when evidence is weak.
 *
 * Matches `SecondRetrievalPlan` in `law_agent/review/schemas.py`.
 */
export interface SecondRetrievalPlan {
  expanded_queries: RetrievalQuery[];
  increased_top_k: number;
  stronger_boost: boolean;
  reason: string;
}

/**
 * Evidence sufficiency state for a review trace.
 *
 * Matches `EvidenceSelfCheck` in `law_agent/review/schemas.py`.
 */
export interface EvidenceSelfCheck {
  status: EvidenceStatus;
  issues: EvidenceIssue[];
  triggered_reasons: string[];
  second_retrieval_triggered: boolean;
  /** Present only when a second retrieval is planned. */
  second_retrieval_plan: SecondRetrievalPlan | null;
}

/**
 * Structured review result produced from facts and evidence.
 *
 * Matches `ReviewResult` in `law_agent/review/schemas.py`.
 */
export interface ReviewResult {
  review_result_id: string;
  review_case_id: string;
  trace_id: string;
  risk_level: RiskLevel;
  conclusion: string;
  review_facts: ReviewFacts;
  trigger_reasons: string[];
  missing_information: string[];
  recommended_actions: string[];
  risk_boundaries: string[];
  claims: GroundedClaim[];
  citations: Citation[];
  /** Evidence grouped by usage category. */
  applicable_evidence: CitationGroup[];
}

/** Structured review result returned inside a persisted case. */
export interface ReviewResponse {
  review_case_id: string;
  trace_id: string;
  review_facts: ReviewFacts;
  review_result: ReviewResult;
  evidence_self_check: EvidenceSelfCheck;
  /** Same value as `review_result.applicable_evidence`, surfaced for convenience. */
  citation_groups: CitationGroup[];
  second_retrieval_triggered: boolean;
  /** Typed retrieval queries planned from the question + facts (query plan). */
  retrieval_queries?: RetrievalQuery[];
  /** Final evidence hits with chunk text, used to expand citations inline. */
  evidence_chunks: RetrievalHit[];
  /** Source-level evidence packets with representative/supporting/neighbor chunks. */
  source_evidence_packets: SourceEvidencePacket[];
}

/**
 * Structured failure response for LLM-owned workflow nodes.
 *
 * The backend intentionally returns this as HTTP 200 so the UI can display
 * which node failed after retries instead of treating it as transport failure.
 */
export interface ReviewFailedResponse {
  status: 'review_failed';
  failed_node: string;
  reason: string;
  message: string;
  attempts: number;
  trace_id: string | null;
}

export type ReviewApiResponse = ReviewResponse | ReviewFailedResponse;

export function isReviewFailedResponse(
  response: ReviewApiResponse | null,
): response is ReviewFailedResponse {
  return Boolean(response && 'status' in response && response.status === 'review_failed');
}

/**
 * Response body for `GET /api/health`.
 *
 * Matches `HealthResponse` in `law_agent/review/api.py`.
 */
export interface HealthResponse {
  status: string;
}

// ---------------------------------------------------------------------------
// CrossComply case workbench models
// ---------------------------------------------------------------------------

export type UserRole = 'requester' | 'reviewer' | 'admin';
export type CaseStatus =
  | 'draft'
  | 'needs_info'
  | 'pending_review'
  | 'review_running'
  | 'pending_feishu_approval'
  | 'approved'
  | 'conditionally_approved'
  | 'rejected'
  | 'run_failed';
export type ActionStatus = 'open' | 'in_progress' | 'completed';
export type ReviewTaskStatus = 'queued' | 'running' | 'succeeded' | 'failed';

/**
 * Independent remediation-plan workflow. These models deliberately stay
 * separate from the legacy CaseAction record used by old case snapshots.
 */
export type RemediationPlanStatus = 'draft' | 'active' | 'completed' | 'cancelled';
export type RemediationTaskStatus = 'open' | 'in_progress' | 'pending_review' | 'completed';
export type RemediationPriority = 'high' | 'medium' | 'low';
export type RemediationEvidenceKind = 'file' | 'case_material' | 'link';
export type RemediationSubmissionStatus = 'pending_review' | 'accepted' | 'rejected';

export interface RemediationAssigneeApi extends WorkbenchUser {
  active?: boolean;
}

export interface RemediationEvidenceApi {
  id: string;
  submission_id?: string;
  kind: RemediationEvidenceKind;
  label: string;
  uri: string | null;
  object_key: string | null;
  content_type?: string | null;
  byte_size: number | null;
  sha256: string | null;
  created_at: string;
}

export interface RemediationSubmissionApi {
  id: string;
  task_id: string;
  submitted_by: string;
  submitted_by_user?: RemediationAssigneeApi | null;
  note: string;
  evidence: RemediationEvidenceApi[];
  status: RemediationSubmissionStatus;
  reviewed_by?: string | null;
  review_note: string | null;
  created_at: string;
  reviewed_at: string | null;
}

export interface RemediationTaskApi {
  id: string;
  plan_id: string;
  case_id: string;
  case_title?: string | null;
  case_question?: string | null;
  title: string;
  description: string;
  acceptance_criteria?: string;
  source_recommendation: string | null;
  source_recommendation_index: number | null;
  assignee_id: string | null;
  assignee?: RemediationAssigneeApi | null;
  priority: RemediationPriority;
  status: RemediationTaskStatus;
  due_date: string | null;
  version?: number;
  submissions?: RemediationSubmissionApi[];
  latest_submission?: RemediationSubmissionApi | null;
  created_at: string;
  updated_at: string;
}

export interface RemediationPlanCountsApi {
  total: number;
  open: number;
  in_progress: number;
  pending_review: number;
  completed: number;
  overdue: number;
}

export interface RemediationPlanApi {
  id: string;
  case_id: string;
  case_title?: string;
  case_status?: CaseStatus;
  status: RemediationPlanStatus;
  created_by: string;
  no_remediation_reason?: string | null;
  version?: number;
  counts?: RemediationPlanCountsApi;
  tasks: RemediationTaskApi[];
  events?: CaseEvent[];
  created_at: string;
  updated_at: string;
}

export interface RemediationInboxItemApi extends RemediationTaskApi {
  case_title?: string;
  case_question?: string;
  plan_status?: RemediationPlanStatus;
}

export interface RemediationPlanCreatePayload {
  tasks: Array<{
    title: string;
    description: string;
    source_recommendation?: string | null;
    source_recommendation_index?: number | null;
    assignee_id: string;
    priority: RemediationPriority;
    due_date: string;
  }>;
}

export interface RemediationTaskUpdatePayload {
  assignee_id?: string;
  priority?: RemediationPriority;
  due_date?: string | null;
}

export interface RemediationSubmissionPayload {
  note: string;
  evidence?: Array<{
    kind: RemediationEvidenceKind;
    label: string;
    uri?: string | null;
    object_key?: string | null;
    content_type?: string | null;
    sha256?: string | null;
    byte_size?: number | null;
  }>;
}

export type RemediationEvidenceUploadApi = NonNullable<RemediationSubmissionPayload['evidence']>[number];

export interface RemediationReviewPayload {
  decision: 'accepted' | 'rejected';
  review_note?: string;
}

export interface MaterialVersionApi {
  id: string;
  material_id: string;
  case_id: string;
  logical_name: string;
  version_number: number;
  filename: string;
  content_type: string;
  object_key: string;
  sha256: string;
  byte_size: number;
  parse_status: 'pending' | 'parsing' | 'ready' | 'failed';
  uploaded_by: string;
  parser: string | null;
  parser_version: string | null;
  parsed_text: string | null;
  created_at: string;
}

export interface MaterialSnapshotApi {
  id: string;
  case_id: string;
  fingerprint: string;
  version_ids: string[];
  created_by: string;
  created_at: string;
}

export interface CandidateCompliancePathApi {
  code: string;
  label: string;
  confidence: 'determined' | 'possible';
  reason: string;
}

export interface MissingFactApi {
  key: string;
  reason: string;
}

export interface RuleHitApi {
  rule_id: string;
  summary: string;
  basis_ids: string[];
}

export interface OfficialBasisApi {
  basis_id: string;
  title: string;
  article: string;
  issuing_body: string;
  source_url: string;
}

export interface ComplianceDecisionApi {
  status: 'determined' | 'needs_info';
  rule_version: string;
  candidate_paths: CandidateCompliancePathApi[];
  needs_info: MissingFactApi[];
  rule_hits: RuleHitApi[];
  official_bases: OfficialBasisApi[];
  requires_rag_human_confirmation: boolean;
  manual_confirmation_reasons: string[];
}

export interface ComplianceFactsApi {
  cross_border_transfer: boolean | null;
  is_ciio: boolean | null;
  important_data: boolean | null;
  contains_personal_information: boolean | null;
  contains_sensitive_personal_information: boolean | null;
  cumulative_personal_information_subjects: number | null;
  cumulative_sensitive_personal_information_subjects: number | null;
  claimed_exemption: 'overseas_data_transit' | 'individual_contract' | 'hr_management' | 'emergency' | null;
  exemption_facts_confirmed: boolean | null;
  special_regimes: Array<'free_trade_zone' | 'greater_bay_area' | 'industry_specific'>;
}

export interface RuleDecisionApi {
  id: string;
  case_id: string;
  material_snapshot_id: string;
  ruleset_version: string;
  facts: ComplianceFactsApi;
  determination: ComplianceDecisionApi;
  created_at: string;
}

export interface ReviewTaskAttemptApi {
  attempt_number: number;
  worker_id: string;
  status: 'running' | 'succeeded' | 'failed';
  failed_node: string | null;
  error_category: string | null;
  error_message: string | null;
  started_at: string;
  finished_at: string | null;
}

export interface ReviewTaskApi {
  id: string;
  case_id: string;
  material_snapshot_id: string;
  rule_snapshot_id: string;
  idempotency_key: string;
  status: ReviewTaskStatus;
  current_node: string | null;
  error_category: string | null;
  error_message: string | null;
  attempt_count: number;
  model_id: string;
  data_boundary_summary: Record<string, unknown>;
  result: Record<string, unknown> | null;
  attempts: ReviewTaskAttemptApi[];
  created_at: string;
  updated_at: string;
}

export interface FeishuApprovalApi {
  id: string;
  case_id: string;
  task_id: string;
  provider: string;
  instance_id: string;
  status: 'pending' | 'approved' | 'conditionally_approved' | 'rejected' | 'withdrawn';
  approver_name: string | null;
  decided_at: string | null;
  payload: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export type SignedDecisionApi = FeishuApprovalApi;

export interface ReportRecordApi {
  id: string;
  case_id: string;
  approval_id: string;
  object_key: string;
  sha256: string;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface FreezeMaterialSnapshotResponse {
  material_snapshot: MaterialSnapshotApi;
  rule_decision: RuleDecisionApi;
}

export interface WorkbenchUser {
  id: string;
  username: string;
  display_name: string;
  role: UserRole;
}

export interface ManagedUserApi extends WorkbenchUser {
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface CaseIntake {
  business_activity: string;
  data_types: string[];
  sensitive_personal_info: boolean | null;
  cross_border_transfer: boolean | null;
  important_data_status: 'unknown' | 'not_important' | 'important' | 'under_review';
  ciio_status: 'unknown' | 'not_ciio' | 'ciio' | 'under_review';
  annual_non_sensitive_count: string;
  annual_sensitive_count: string;
  overseas_recipient: string;
  destination_region: string;
  processing_purpose: string;
  transfer_mechanism: string;
  vendor_name: string;
  contract_status: string;
  legal_basis_or_consent: string;
  notes: string;
}

export interface CaseAction {
  id: string;
  case_id: string;
  title: string;
  description: string;
  owner_role: string;
  priority: 'high' | 'medium' | 'low';
  status: ActionStatus;
  due_date: string | null;
  created_at: string;
  updated_at: string;
}

export interface CaseEvent {
  id: string;
  case_id: string;
  actor_id: string;
  event_type: string;
  from_status: CaseStatus | null;
  to_status: CaseStatus | null;
  payload: Record<string, unknown>;
  created_at: string;
}

export interface CaseFeedbackApi {
  case_id: string;
  actor_id: string;
  conclusion_useful: boolean | null;
  missing_sources: string;
  notes: string;
  citation_verdicts: Record<string, 'correct' | 'wrong'>;
  updated_at: string;
}

export interface CaseSummaryApi {
  id: string;
  title: string;
  question: string;
  status: CaseStatus;
  risk_level: RiskLevel | null;
  facts_confirmed: boolean;
  created_by: string;
  owner_id: string | null;
  created_at: string;
  updated_at: string;
  has_result: boolean;
}

export interface CaseRecordApi extends CaseSummaryApi {
  material_text: string;
  material_source: string | null;
  intake: CaseIntake;
  review_mode: 'llm' | 'multi_agent';
  rerank_mode: 'off' | 'embedding';
  trace_id: string | null;
  response: ReviewApiResponse | null;
}

export interface CaseDetailApi {
  case: CaseRecordApi;
  /** Legacy field may be absent; current remediation data lives in remediation_plan. */
  actions?: CaseAction[];
  events: CaseEvent[];
  feedback: CaseFeedbackApi | null;
  material_snapshot: MaterialSnapshotApi | null;
  rule_decision: RuleDecisionApi | null;
  review_task: ReviewTaskApi | null;
  feishu_approval: FeishuApprovalApi | null;
  signed_decision: SignedDecisionApi | null;
  report: ReportRecordApi | null;
  remediation_plan?: RemediationPlanApi | null;
}

export interface CaseListApi {
  items: CaseSummaryApi[];
  total: number;
}

export interface DashboardSummaryApi {
  total_cases: number;
  status_counts: Record<CaseStatus, number>;
  risk_counts: Record<string, number>;
  recent_cases: CaseSummaryApi[];
}

// ---------------------------------------------------------------------------
// Evaluation suite models
// ---------------------------------------------------------------------------

/**
 * Metrics for a single evaluation scenario case.
 *
 * Matches `CaseMetricResult` in `law_agent/review/evalset/schemas.py`.
 */
export interface CaseMetricResult {
  case_id: string;
  recall_at_3: number | null;
  recall_at_5: number | null;
  mrr_at_10: number | null;
  candidate_recall_at_50: number | null;
  distinct_source_recall_at_5: number | null;
  duplicate_source_count_at_10: number;
  citation_violation_count: number;
  abstention_correct: boolean;
  /** 是否触发了二次检索。 */
  second_retrieval_triggered: boolean;
  /** Source IDs actually retrieved by the system. */
  actual_sources: string[];
  /** Expected source IDs that were missing from the results. */
  missing_sources: string[];
  is_bad_case: boolean;
  bad_reasons: string[];
  risk_level: string;
  /** Must-have Recall@5 — null for abstention/out-of-corpus cases. */
  must_have_recall_at_5: number | null;
  /** Optional coverage@5 — null when the case has no optional sources. */
  optional_coverage_at_5: number | null;
}

/**
 * Aggregated metrics for one retrieval mode.
 *
 * Matches `ModeMetrics` in `law_agent/review/evalset/schemas.py`.
 */
export interface ModeMetrics {
  mode: string;
  mean_recall_at_3: number;
  mean_recall_at_5: number;
  mean_mrr_at_10: number;
  mean_candidate_recall_at_50: number;
  mean_distinct_source_recall_at_5: number;
  mean_duplicate_source_count_at_10: number;
  abstention_accuracy: number;
  /** 诊断指标：二次检索触发率（不计坏例）。 */
  second_retrieval_trigger_rate: number;
  total_citation_violations: number;
  bad_case_count: number;
  total_cases: number;
  /** Must-have Recall@5 均值（仅含有 must-have 源的案例）。 */
  mean_must_have_recall_at_5: number;
  must_have_case_count: number;
  /** Optional coverage@5 均值（仅含有 optional 源的案例）。 */
  mean_optional_coverage_at_5: number;
  optional_supporting_case_count: number;
  source_bearing_case_count: number;
}

/**
 * Full evaluation summary output.
 *
 * Matches `EvalSummary` in `law_agent/review/evalset/schemas.py`. Returned
 * by both `POST /api/eval/run` and `GET /api/eval/latest`.
 */
export interface EvalSummary {
  generated_at: string;
  chunks_path: string;
  cases_path: string;
  /** Aggregated metrics keyed by explicit eval axes. */
  mode_metrics: Record<string, ModeMetrics>;
  bad_cases: CaseMetricResult[];
  /** Per-case results keyed by mode name. */
  all_case_results: Record<string, CaseMetricResult[]>;
}

/** Request body for `POST /api/eval/run`. */
export interface EvalRunOptions {
  chunks_path?: string;
  retrieval_mode?: EvalRetrievalMode;
  review_mode?: EvalReviewMode;
  top_k?: number;
  max_workers?: number;
  rerank_mode?: EvalRerankMode;
  suite?: EvalSuite;
}

export type EvalJobStatus = 'idle' | 'running' | 'succeeded' | 'failed';

export interface EvalJobResponse {
  job_id: string | null;
  status: EvalJobStatus;
  message: string | null;
  started_at: string | null;
  finished_at: string | null;
}
